<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-python/blob/main/01_Numpy_Arrays_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,21,2)#start,stop,step
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
b=a**2  #List Squares
b

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [ ]:
arr=np.linspace(1,10,4)#start,stop,num of values between them
arr

array([ 1.,  4.,  7., 10.])

In [ ]:
np.logspace(1,2,3)

array([ 10.       ,  31.6227766, 100.       ])

In [ ]:
#np.zeroes --> full of zeros
# np.zeros(12)
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.ones([2,2,4],dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
arr=np.full([3,3],6)

In [ ]:
b=np.empty([2,3])
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(10)

array([0.65127362, 0.01813781, 0.25998005, 0.28875203, 0.55124162,
       0.97777454, 0.99907087, 0.41014958, 0.35231533, 0.07266688])

In [ ]:
np.random.rand(2,3)

array([[0.12785621, 0.80624027, 0.45657477],
       [0.14028799, 0.10927754, 0.40695967]])

In [ ]:
np.random.randn(3,3)#random floats from standard deviation average =0 and std=1

array([[-0.63964883,  0.7600979 , -0.05286233],
       [ 0.24385482, -0.00600688, -1.69147629],
       [ 1.04726563,  0.53337831, -0.2744161 ]])

In [ ]:
np.random.randint(1,100)

53

In [ ]:
np.random.randint(1,100,(3,4))  #start,stop,size/dimension

array([[22, 15, 81, 31],
       [48, 62, 16,  5],
       [18, 47, 70, 37]])


Numpy Data Types and Type Casting

In [ ]:
list=[1,2,3,"MAnoj"]
arr=np.array(list)
arr

array(['1', '2', '3', 'MAnoj'], dtype='<U21')

In [ ]:
a=np.array([1,2,3.1,3,"5"],dtype=str)       #dtype converts the list into given datatype
a

array(['1', '2', '3.1', '3', '5'], dtype='<U3')

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
new_arr=arr.astype(np.float64)
new_arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr2=new_arr.astype(np.str_)
arr2

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

In [ ]:
# Type casting errors
a=np.array(["1","2",'Hello'])
a
# a.astype(np.int64) it'll give an error it can't convert hello into integer

array(['1', '2', 'Hello'], dtype='<U5')

In [ ]:
new=np.array([[1,2,3],[4,5,6]])
new

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
new.ndim

2

In [ ]:
new.shape

(2, 3)

In [ ]:
new.size

6

In [ ]:
new.itemsize

8

In [ ]:
new.itemsize*new.size

48